/'This file is used to generate the usecase diagram with plantuml. To generate it from the command line run'/
/'java -jar plantuml.jar usecasediagram.txt'/
/'Make sure you [download PlantUML first](https://plantuml.com/download)'/
@startuml
!theme plain
left to right direction
actor User
rectangle "Virtual Fridge" << System >> {
  usecase logOcr as "Log Food via OCR"
  usecase logFood as "Log Food"
  usecase logBarcode as "Log Food via Barcode"


  logBarcode .> logFood : << extend >>
  logOcr .> logFood: << extend >>

  usecase viewNutrition as "View Nutritional facts"
  usecase signUp as "Sign up with Google"
  usecase viewFridge as "View Fridge"
  usecase generateRecipes as "Generate Recipe Suggestions"
}
User -- signUp
User -- logFood
User -- viewFridge
User -- generateRecipes
User -- viewNutrition
rectangle openFoodFacts as "Open Food Facts API"
rectangle googleAuth as "Google Authentication"
rectangle recipeApi as "TheMealDB API"
rectangle barcodeScanner as "Barcode Scanner"
generateRecipes -- recipeApi
viewNutrition -- openFoodFacts
signUp -- googleAuth
logBarcode -- barcodeScanner
logFood -- openFoodFacts
@enduml
